version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: awsde-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - airflow

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: awsde-airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      # So Python can see your project at /opt/airflow
      PYTHONPATH: /opt/airflow
    volumes:
      # Mount entire project so /opt/airflow/etl exists
      - ./:/opt/airflow
      # Mount DAGs folder to standard Airflow DAsGs path
      - ./airflow-bestbuy/dags:/opt/airflow/dags
      # Logs folder for Airflow logs
      - ./airflow-bestbuy/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - airflow

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: awsde-airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow
    volumes:
      - ./:/opt/airflow
      - ./airflow-bestbuy/dags:/opt/airflow/dags
      - ./airflow-bestbuy/logs:/opt/airflow/logs
    command: scheduler
    networks:
      - airflow

networks:
  airflow:

volumes:
  postgres-db-volume:
